site_name: InfraX
site_url: https://infrax.network
site_description: Distributing power through the facilitation of GPU and AI Resources
site_author: InfraX Network
repo_url: https://github.com/InfraX-network/infrax_docs
repo_name: infrax-network/infrax_docs
copyright: Copyright &copy; 2024 - InfraX
extra:
  social:
    - icon: material/github
      link: https://github.com/InfraX-network/infrax_docs
    - icon: material/twitter
      link: https://twitter.com/InfraX_
    - icon: simple/telegram
      link: https://t.me/infraxai
plugins:
  - social
theme:
  name: material
  logo: img/Favicons (favicon)/favicon-192.png
  favicon: img/Favicons (favicon)/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: '(prefers-color-scheme)'
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode

    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: black
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Node: node.md
  - App: app.md
  - Job: job.md
